# standard fields that are set based on sampling site
ENV_LOOKUP = {
    'Animal Habitat':
    {'SAMPLE_GROUP': 'animal habitat',
     'SCIENTIFIC_NAME': 'metagenome',
     'TAXON_ID': '256318',
     'ENV_MATERIAL': 'animal-associated habitat',
     'ENV_PACKAGE': 'host-associated',
     'ENV_FEATURE': 'animal-associated habitat',
     'ENV_BIOME': 'dense settlement biome',
     'DESCRIPTION': 'American Gut Project animal habitat sample',
     'SAMPLE_TYPE': 'animal-associated'
     },
    'Biofilm':
    {'SAMPLE_GROUP': 'biofilm',
     'SCIENTIFIC_NAME': 'biofilm metagenome',
     'TAXON_ID': '718308',
     'ENV_MATERIAL': 'organic material',
     'ENV_PACKAGE': 'microbial mat/biofilm',
     'ENV_FEATURE': 'biofilm',
     'ENV_BIOME': 'dense settlement biome',
     'DESCRIPTION': 'American Gut Project biofilm sample',
     'SAMPLE_TYPE': 'biofilm'
     },
    'Dust':
    {'SAMPLE_GROUP': 'indoor',
     'SCIENTIFIC_NAME': 'Dust metagenome',
     'TAXON_ID': '1236744',
     'ENV_MATERIAL': 'dust',
     'ENV_PACKAGE': 'built-environment',
     'ENV_FEATURE': 'environmental material',
     'ENV_BIOME': 'dense settlement biome',
     'DESCRIPTION': 'American Gut Project dust sample',
     'SAMPLE_TYPE': 'dust'
     },
    'Food':
    {'SAMPLE_GROUP': 'food',
     'SCIENTIFIC_NAME': 'food metagenome',
     'TAXON_ID': '870726',
     'ENV_MATERIAL': 'food product',
     'ENV_PACKAGE': 'misc environment',
     'ENV_FEATURE': 'anthropogenic environmental material',
     'ENV_BIOME': 'dense settlement biome',
     'DESCRIPTION': 'American Gut Project food sample',
     'SAMPLE_TYPE': 'food'
     },
    'Fermented Food':
    {'SAMPLE_GROUP': 'food',
     'SCIENTIFIC_NAME': 'Food fermentation metagenome',
     'TAXON_ID': '1154581',
     'ENV_MATERIAL': 'fermented food product',
     'ENV_PACKAGE': 'misc environment',
     'ENV_FEATURE': 'anthropogenic environmental material',
     'ENV_BIOME': 'dense settlement biome',
     'DESCRIPTION': 'American Gut Project fermented food sample',
     'SAMPLE_TYPE': 'food'
     },
    'Indoor Surface':
    {'SAMPLE_GROUP': 'indoor',
     'SCIENTIFIC_NAME': 'Indoor metagenome',
     'TAXON_ID': '1256227',
     'ENV_MATERIAL': 'dust',
     'ENV_PACKAGE': 'built environment',
     'ENV_FEATURE': 'building',
     'ENV_BIOME': 'dense settlement biome',
     'DESCRIPTION': 'American Gut Project indoor surface sample',
     'SAMPLE_TYPE': 'dust'
     },
    'Outdoor Surface':
    {'SAMPLE_GROUP': 'outdoor',
     'SCIENTIFIC_NAME': 'ecological metagenome',
     'TAXON_ID': '410657',
     'ENV_MATERIAL': 'surface layer',
     'ENV_PACKAGE': 'misc environment',
     'ENV_FEATURE': 'building',
     'ENV_BIOME': 'dense settlement biome',
     'DESCRIPTION': 'American Gut Project outdoor surface sample',
     'SAMPLE_TYPE': 'surface'
     },
    'Plant habitat':
    {'SAMPLE_GROUP': 'outdoor',
     'SCIENTIFIC_NAME': 'plant metagenome',
     'TAXON_ID': '1297885',
     'ENV_MATERIAL': 'organic material',
     'ENV_PACKAGE': 'plant-associated',
     'ENV_FEATURE': 'environmental material',
     'ENV_BIOME': 'dense settlement biome',
     'DESCRIPTION': 'American Gut Project plant habitat sample',
     'SAMPLE_TYPE': 'plant'
     },
    'Soil':
    {'SAMPLE_GROUP': 'outdoor',
     'SCIENTIFIC_NAME': 'soil metagenome',
     'TAXON_ID': '410658',
     'ENV_MATERIAL': 'soil',
     'ENV_PACKAGE': 'soil',
     'ENV_FEATURE': 'soil',
     'ENV_BIOME': 'dense settlement biome',
     'DESCRIPTION': 'American Gut Project soil sample',
     'SAMPLE_TYPE': 'soil'
     },
    'Sole of shoe':
    {'SAMPLE_GROUP': 'indoor',
     'SCIENTIFIC_NAME': 'Dust metagenome',
     'TAXON_ID': '1236744',
     'ENV_MATERIAL': 'dust',
     'ENV_PACKAGE': 'built-environment',
     'ENV_FEATURE': 'anthropogenic environmental material',
     'ENV_BIOME': 'dense settlement biome',
     'DESCRIPTION': 'American Gut Project dust sample',
     'SAMPLE_TYPE': 'dust'
     },
    'Water':
    {'SAMPLE_GROUP': 'water',
     'SCIENTIFIC_NAME': 'freshwater metagenome',
     'TAXON_ID': '449393',
     'ENV_MATERIAL': 'water',
     'ENV_PACKAGE': 'water',
     'ENV_FEATURE': 'environmental material',
     'ENV_BIOME': 'dense settlement biome',
     'DESCRIPTION': 'American Gut Project water sample',
     'SAMPLE_TYPE': 'water'
     }
}


HUMAN_SITE_INVARIANTS = {
    'Blood (skin prick)':
        {'BODY_PRODUCT': 'UBERON:sebum',
         'SAMPLE_TYPE': 'Blood (skin prick)',
         'SCIENTIFIC_NAME': 'human blood',
         'TAXON_ID': 'NA',
         'BODY_HABITAT': 'UBERON:blood',
         'ENV_MATERIAL': 'blood',
         'ENV_PACKAGE': 'human-associated',
         'DESCRIPTION': 'American Gut Project blood skin prick sample',
         'BODY_SITE': 'UBERON:blood'},
    'Hair':
        {'BODY_PRODUCT': 'UBERON:sebum',
         'SAMPLE_TYPE': 'Hair',
         'SCIENTIFIC_NAME': 'human skin metagenome',
         'TAXON_ID': '539655',
         'BODY_HABITAT': 'UBERON:hair',
         'ENV_MATERIAL': 'sebum',
         'ENV_PACKAGE': 'human-associated',
         'DESCRIPTION': 'American Gut Project Hair sample',
         'BODY_SITE': 'UBERON:hair'},
    'Nares': {
        'BODY_PRODUCT': 'UBERON:mucus',
        'SAMPLE_TYPE': 'Nares',
        'SCIENTIFIC_NAME': 'human nasal/pharyngeal metagenome',
        'TAXON_ID': '1131769',
        'BODY_HABITAT': 'UBERON:nose',
        'ENV_MATERIAL': 'mucus',
        'ENV_PACKAGE': 'human-skin',
        'DESCRIPTION': 'American Gut Project Nares sample',
        'BODY_SITE': 'UBERON:nostril'},
    'Vaginal mucus': {
        'BODY_PRODUCT': 'UBERON:mucus',
        'SAMPLE_TYPE': 'Vaginal mucus',
        'SCIENTIFIC_NAME': 'human vaginal metagenome',
        'TAXON_ID': '1632839',
        'BODY_HABITAT': 'UBERON:vagina',
        'ENV_MATERIAL': 'mucus',
        'ENV_PACKAGE': 'human-vaginal',
        'DESCRIPTION': 'American Gut Project Vaginal mucus sample',
        'BODY_SITE': 'UBERON:vaginal introitus'},
    'Sole of foot': {
        'BODY_PRODUCT': 'UBERON:sebum',
        'SAMPLE_TYPE': 'Sole of foot',
        'SCIENTIFIC_NAME': 'human skin metagenome',
        'TAXON_ID': '539655',
        'BODY_HABITAT': 'UBERON:skin',
        'ENV_MATERIAL': 'sebum',
        'ENV_PACKAGE': 'human-skin',
        'DESCRIPTION': 'American Gut Project Sole of foot sample',
        'BODY_SITE': 'UBERON:skin of foot'},
    'Nasal mucus': {
        'BODY_PRODUCT': 'UBERON:mucus',
        'SAMPLE_TYPE': 'Mucus',
        'SCIENTIFIC_NAME': 'human nasal/pharyngeal metagenome',
        'TAXON_ID': '1131769',
        'BODY_HABITAT': 'UBERON:nose',
        'ENV_MATERIAL': 'mucus',
        'ENV_PACKAGE': 'human-associated',
        'DESCRIPTION': 'American Gut Project Nasal mucus sample',
        'BODY_SITE': 'UBERON:nostril'},
    'Stool': {
        'BODY_PRODUCT': 'UBERON:feces',
        'SAMPLE_TYPE': 'Stool',
        'SCIENTIFIC_NAME': 'human gut metagenome',
        'TAXON_ID': '408170',
        'BODY_HABITAT': 'UBERON:feces',
        'ENV_MATERIAL': 'feces',
        'ENV_PACKAGE': 'human-gut',
        'DESCRIPTION': 'American Gut Project Stool sample',
        'BODY_SITE': 'UBERON:feces'},
    'Forehead': {
        'BODY_PRODUCT': 'UBERON:sebum',
        'SAMPLE_TYPE': 'Forehead',
        'SCIENTIFIC_NAME': 'human skin metagenome',
        'TAXON_ID': '539655',
        'BODY_HABITAT': 'UBERON:skin',
        'ENV_MATERIAL': 'sebum',
        'ENV_PACKAGE': 'human-skin',
        'DESCRIPTION': 'American Gut Project Forehead sample',
        'BODY_SITE': 'UBERON:skin of head'},
    'Tears': {
        'BODY_PRODUCT': 'UBERON:tears',
        'SAMPLE_TYPE': 'Tears',
        'SCIENTIFIC_NAME': 'human eye metagenome',
        'TAXON_ID': '1774142',
        'BODY_HABITAT': 'UBERON:eye',
        'ENV_MATERIAL': 'tears',
        'ENV_PACKAGE': 'human-associated',
        'DESCRIPTION': 'American Gut Project Tears sample',
        'BODY_SITE': 'UBERON:eye'},
    'Right hand': {
        'BODY_PRODUCT': 'UBERON:sebum',
        'SAMPLE_TYPE': 'Right Hand',
        'SCIENTIFIC_NAME': 'human skin metagenome',
        'TAXON_ID': '539655',
        'BODY_HABITAT': 'UBERON:skin',
        'ENV_MATERIAL': 'sebum',
        'ENV_PACKAGE': 'human-skin',
        'DESCRIPTION': 'American Gut Project Right Hand sample',
        'BODY_SITE': 'UBERON:skin of hand'},
    'Axilla': {
        'BODY_PRODUCT': 'UBERON:sebum',
        'SAMPLE_TYPE': 'Axilla',
        'SCIENTIFIC_NAME': 'human skin metagenome',
        'TAXON_ID': '539655',
        'BODY_HABITAT': 'UBERON:skin',
        'ENV_MATERIAL': 'sebum',
        'ENV_PACKAGE': 'human-skin',
        'DESCRIPTION': 'American Gut Project Right Axilla sample',
        'BODY_SITE': 'UBERON:skin of axilla'},
    'Torso': {
        'BODY_PRODUCT': 'UBERON:sebum',
        'SAMPLE_TYPE': 'Torso',
        'SCIENTIFIC_NAME': 'human skin metagenome',
        'TAXON_ID': '539655',
        'BODY_HABITAT': 'UBERON:skin',
        'ENV_MATTER': 'sebum',
        'DESCRIPTION': 'American Gut Project torso sample',
        'BODY_SITE': 'UBERON:skin of trunk'},
    'Left leg': {
        'BODY_PRODUCT': 'UBERON:sebum',
        'SAMPLE_TYPE': 'Left leg',
        'SCIENTIFIC_NAME': 'human skin metagenome',
        'TAXON_ID': '539655',
        'BODY_HABITAT': 'UBERON:skin',
        'ENV_MATTER': 'sebum',
        'DESCRIPTION': 'American Gut Project left leg sample',
        'BODY_SITE': 'UBERON:skin of leg'},
    'Right leg': {
        'BODY_PRODUCT': 'UBERON:sebum',
        'SAMPLE_TYPE': 'Right leg',
        'SCIENTIFIC_NAME': 'human skin metagenome',
        'TAXON_ID': '539655',
        'BODY_HABITAT': 'UBERON:skin',
        'ENV_MATTER': 'sebum',
        'DESCRIPTION': 'American Gut Project right leg sample',
        'BODY_SITE': 'UBERON:skin of leg'},
    'Mouth': {
        'BODY_PRODUCT': 'UBERON:saliva',
        'SAMPLE_TYPE': 'Mouth',
        'SCIENTIFIC_NAME': 'human oral metagenome',
        'TAXON_ID': '447426',
        'BODY_HABITAT': 'UBERON:oral cavity',
        'ENV_MATERIAL': 'saliva',
        'ENV_PACKAGE': 'human-oral',
        'DESCRIPTION': 'American Gut Project Mouth sample',
        'BODY_SITE': 'UBERON:tongue'},
    'Left hand': {
        'BODY_PRODUCT': 'UBERON:sebum',
        'SAMPLE_TYPE': 'Left Hand',
        'SCIENTIFIC_NAME': 'human skin metagenome',
        'TAXON_ID': '539655',
        'BODY_HABITAT': 'UBERON:skin',
        'ENV_MATERIAL': 'sebum',
        'ENV_PACKAGE': 'human-skin',
        'DESCRIPTION': 'American Gut Project Left Hand sample',
        'BODY_SITE': 'UBERON:skin of hand'},
    'Ear wax': {
        'BODY_PRODUCT': 'UBERON:cerumen',
        'SAMPLE_TYPE': 'Ear wax',
        'SCIENTIFIC_NAME': 'human metagenome',
        'TAXON_ID': '646099',
        'BODY_HABITAT': 'UBERON:ear',
        'ENV_MATERIAL': 'ear wax',
        'ENV_PACKAGE': 'human-associated',
        'DESCRIPTION': 'American Gut Project Ear wax sample',
        'BODY_SITE': 'UBERON:external auditory meatus'}
}


for site in HUMAN_SITE_INVARIANTS.values():
    site.update({
        'HOST_TAXID': '9606',
        'SCIENTIFIC_NAME': 'Homo sapiens',
        'TITLE': 'American Gut Project',
        'ASSIGNED_FROM_GEO': 'Yes',
        'ENV_BIOME': 'dense settlement biome',
        'ENV_FEATURE': 'human-associated habitat',
        'DNA_EXTRACTED': 'Yes',
        'PHYSICAL_SPECIMEN_REMAINING': 'Yes',
        'PHYSICAL_SPECIMEN_LOCATION': 'UCSDMI',
        'HOST_COMMON_NAME': 'human'})

